dist: xenial
language: bash
before_install:
          - sudo add-apt-repository ppa:duggan/bats --yes
              - sudo apt-get update -qq
                  - sudo apt-get install -qq bats
compiler:
          - gcc
install:
          - make clean
              - make all
script:
          - bats *bats 
